sudo: required
services:
  - docker

before_install:
  - docker build -t nouredine/docker-react -f Dockerfile.dev .

script:
  - docker run nouredine/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "react-docker-europe"
  env: "React-docker-europe-env"
  bucket_name: "elasticbeanstalk-eu-west-3-593111263657"
  bucket_path: "react-docker-europe"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
