sudo: required
services:
  - docker

before_install:
  - docker build -t nouredine/docker-react -f Dockerfile.dev .

script:
  - docker run nouredine/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-with-docker"
  env: "react-with-docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-593111263657"
  bucket_path: "react-with-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  # secret_access_key:
  #   secure: $AWS_SECRET_KEY   docker-react-travis-ci
  # bucket_name: "elasticbeanstalk-us-east-2-593111263657"
