sudo: required
services:
  - docker

before_install:
  - docker build -t nouredine/docker-react -f Dockerfile.dev .

script:
  - docker run nouredine/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-and-docker"
  env: "react-and-docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-593111263657"
  bucket_path: "react-and-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
